import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta 
        property = "og:image"
        content = "https://aiueo-lac.vercel.app/api/og?title=Vercel%E3%82%8F%E3%81%A3%E3%81%97%E3%82%87%E3%81%84%EF%BC%81"
      />
      <body>
        {children}
      </body>
    </html>
  );
}
