import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta 
        property = "og:image"
        content = "https://og-examples.vercel.sh/api/static"
      />
      <body>
        {children}
      </body>
    </html>
  );
}
